# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- task: UiPathRunJob@2
  inputs:
    orchestratorConnection: 'ConnectioOrch'
    processName: 'BlankProcess2'
    folderName: 'Dev'
